### ISSUE TITLE
The plugin failing with error: header field value cannot include CR/LF (ArgumentError)

### ISSUE THREAD

**Issue by dnazila** [mitchellh/vagrant-google#201] opened 2018-06-01 22:35 UTC
This seems to be related to a recent change in Ruby that has banned CR/LFs in HTTP header fields.
For reference take a look at: https://github.com/google/google-api-ruby-client/pull/648

Tested with vagrant 2.1.1

The error looks like this:

# vagrant up --provider=google
/opt/vagrant/embedded/lib/ruby/2.4.0/net/http/header.rb:23:in `block in initialize_http_header': header field value cannot include CR/LF (ArgumentError)
        from /opt/vagrant/embedded/lib/ruby/2.4.0/net/http/header.rb:16:in `each'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/net/http/header.rb:16:in `initialize_http_header'
        from /opt/vagrant/embedded/lib/ruby/2.4.0/net/http/generic_request.rb:44:in `initialize'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:67:in `new'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:67:in `create_request'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:87:in `perform_request'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:43:in `block in call'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:92:in `with_net_http_connection'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/adapter/net_http.rb:38:in `call'
        from /root/.vagrant.d/gems/2.4.4/gems/faraday-0.15.2/lib/faraday/response.rb:8:in `call'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client/request.rb:163:in `send'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client.rb:648:in `block (2 levels) in execute!'
        from /root/.vagrant.d/gems/2.4.4/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
        from /root/.vagrant.d/gems/2.4.4/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client.rb:645:in `block in execute!'
        from /root/.vagrant.d/gems/2.4.4/gems/retriable-1.4.1/lib/retriable/retry.rb:27:in `perform'
        from /root/.vagrant.d/gems/2.4.4/gems/retriable-1.4.1/lib/retriable.rb:15:in `retriable'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client.rb:636:in `execute!'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client.rb:368:in `discovery_document'
        from /root/.vagrant.d/gems/2.4.4/gems/google-api-client-0.8.7/lib/google/api_client.rb:413:in `discovered_api'
        from /root/.vagrant.d/gems/2.4.4/gems/fog-google-0.0.9/lib/fog/google/compute.rb:1063:in `initialize'
        from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
        from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.45.0/lib/fog/core/service.rb:115:in `new'
        from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.45.0/lib/fog/core/services_mixin.rb:16:in `new'
        from /root/.vagrant.d/gems/2.4.4/gems/fog-core-1.45.0/lib/fog/compute.rb:54:in `new'
        from /root/.vagrant.d/gems/2.4.4/gems/vagrant-google-0.2.3/lib/vagrant-google/action/connect_google.rb:45:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/warden.rb:34:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/builder.rb:116:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `block in run'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/util/busy.rb:19:in `busy'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/action/runner.rb:66:in `run'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:239:in `action_raw'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:208:in `block in action'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:598:in `lock'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `call'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:194:in `action'
        from /root/.vagrant.d/gems/2.4.4/gems/vagrant-google-0.2.3/lib/vagrant-google/provider.rb:45:in `state'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:526:in `state'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/machine.rb:146:in `initialize'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/vagrantfile.rb:79:in `new'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/vagrantfile.rb:79:in `machine'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:700:in `machine'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:180:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:204:in `block in with_target_vms'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:186:in `each'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/plugin/v2/command.rb:186:in `with_target_vms'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/plugins/commands/up/command.rb:87:in `execute'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/cli.rb:54:in `execute'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/lib/vagrant/environment.rb:275:in `cli'
        from /opt/vagrant/embedded/gems/2.1.1/gems/vagrant-2.1.1/bin/vagrant:156:in `<main>'

**Comment by Temikus** [comment] 2018-06-05 10:11
Acknowledged. Thanks for filing this issue!

This’ll require a bit of work since fog sets the google-api-client dependency.

I have some time this weekend for it so will try to attend to it.

**Comment by Temikus** [comment] 2018-06-07 07:52
Note that my current understanding of the issue is that it affects only the most recent version of Vagrant, but it’s at the top of my stack to fix.

If you experienced otherwise and this is more serious - let me know and I’ll try to carve out more time for it ASAP.

**Comment by Temikus** [comment] 2018-06-07 10:49
Pending https://github.com/fog/fog-google/pull/354 - need to wait for integration tests to finish and see if this breaks anything since historically there have been very major differences between minor versions of google-api-client.

**Comment by Temikus** [comment] 2018-06-07 11:55
Ran into some issues integrating the patch. Seems fixed now, but tests take a while, will take a fresh look next morning.

**Comment by Temikus** [comment] 2018-06-07 23:56
Pending fog release: https://github.com/fog/fog-google/pull/355

**Closed** 2018-06-08 07:11 UTC

**Comment by Temikus** [comment] 2018-06-08 07:18
Just pushed 2.2.0, you should now be unblocked. Let me know if you still have issues though.
