### ISSUE TITLE
external_ip not working for Static IPs

### ISSUE THREAD

**Issue by Tusharsb** [mitchellh/vagrant-google#34] opened 2015-03-16 07:19 UTC
My Vagrant file contains the following block

    google.zone_config "us-central1-a" do |zone1|
        zone1.external_ip = "123.123.123.123"
    end

(the IP has been masked in above code).

I had an 'unallocated Static IP' in my Google Cloud account. Specifying that static IP in my vagrant file does not makes google cloud to assign the IP to my newly created vagrant box. After my vagrant box got up successfully, I had to manully use the UI of Google Cloud Console, and attach the static IP to my vagrant box. Is this a bug ?

Note that I did tried this code as well (as advised in README.md), but that was returning bug:

    google.external_ip = "123.123.123.123"

**Comment by invernizzi** [comment] 2015-03-19 22:24
Hi,
I had the same issue :) 
This is not actually a bug; simply, the released version of this plugin doesn't yet support external IPs, only the code in master does.
You can quickly check if your version supports external IPs. When doing a `vagrant up`, you should see:
```
==> vm: Launching an instance with the following settings...
[...]
==> vm:  -- IP Forward:      
==> vm:  -- External IP:     107.1XX.XXX.XXX
```
To solve this, I've installed the github version, and it has been working smoothly :)

Ciao!

**Comment by Temikus** [comment] 2015-04-15 16:21
Sorry, but I cannot reproduce the behaviour that you suggested:

1) First try, my config (excerpt):
...
   google.external_ip = "xxx.xxx.xx.xxx"

    google.zone = "europe-west1-d"

    google.zone_config "europe-west1-d" do |zone1d|
        zone1d.name = "testing-vagrant"
        zone1d.image = "debian-7-wheezy-v20150127"
        zone1d.zone = "europe-west1-d"
        zone1d.disk_type = "pd-ssd"
    end
...
Result:
Machine is up and has the IP xxx.xxx.xx.xxx
2) Second try, my config: 
...
    google.zone_config "europe-west1-d" do |zone1d|
        zone1d.name = "testing-vagrant"
        zone1d.image = "debian-7-wheezy-v20150127"
        zone1d.zone = "europe-west1-d"
        zone1d.disk_type = "pd-ssd"
        zone1d.external_ip = "xxx.xxx.xx.xxx"
    end
...
Result:
Machine is up and has the IP xxx.xxx.xx.xxx

Can you elaborate on your setup? What version of Vagrant are you using and what plugin version (or is it compiled from master)?

Thanks.

**Comment by invernizzi** [comment] 2015-04-15 17:03
Hi,
you have to use the plugin directly installed from github (master branch), this feature has not been released as a packaged plugin yet.
To check that you have the right version, execute:

    grep 'external_ip' ~/.vagrant.d/gems/gems/vagrant-google*/lib/vagrant-google/action/run_instance.rb 

You should get several mentions of `external_ip`. If you don't, your plugin is not recent enough.

**Comment by Temikus** [comment] 2015-04-24 16:41
Cannot reproduce, so resolving for now. @tusharsb feel free to reopen though if you see any issues. Thanks for reporting!

/CC @erjohnso 
This can be closed for now.

**Comment by erjohnso** [comment] 2015-04-24 16:47
@Temikus - it appears I need to push out a new gem and then we can close this, correct?

**Comment by Temikus** [comment] 2015-04-24 19:51
@erjohnso This is not really an issue in the codebase, but it is not indeed pushed in the gem, so sure, I will CC you to close it when we push a release out.

**Comment by Temikus** [comment] 2015-05-07 19:04
0.1.5 is out this issue can now be closed.
/CC @erjohnso

**Closed** 2015-05-07 20:24 UTC
