### ISSUE TITLE
Fails to initialize the google API ruby client

### ISSUE THREAD

**Issue by kulkarni-bhaskar** [mitchellh/vagrant-google#29] opened 2015-02-04 12:00 UTC
Says either path to file is incorrect or incorrect passphrase while reading private key

**Comment by erjohnso** [comment] 2015-02-04 13:01
Hi @kulkarni-bhaskar - can you give a bit more detail so I can try to reproduce the problem?  What platform are you using, how did you install vagrant and the plugin, did you use the P12 file from Google, or generate your own?  Can you share your Vagrantfile (scrubbing out personal data)?

**Comment by kulkarni-bhaskar** [comment] 2015-02-04 13:10
Almost followed the steps mentioned on the plugin page
Machine details 
Windows 7 E SP 1 
vagrant version 1.7.2
installed the plugin as 
vagrant install plugin vagrant-docker

============================
Vagrant file provider settings

  config.vm.box = "gce"
   config.vm.provider :google do |google, override|
      google.google_project_id = "xxxxapp"
      google.google_client_email = "xxxxxxxxxxxxxxkd0snpeinv@developer.gserviceaccount.com"
      google.google_key_location = "xxxxxx17461a6c47ce.p2"
      #google.passphrase = "xxxxxxx"
  
      #override.ssh.username = "vagrant"
      #override.ssh.private_key_path = "~/.ssh/id_boot2docker"
      #override.ssh.private_key_path = "~/.ssh/google_compute_engine"
    end

===========================

once I say vagrant up --provider=google
This is the error I get 
C:\dev-image.git>vagrant up --provider=google
C:/Users/sinbkk/.vagrant.d/gems/gems/google-api-client-0.8.2/lib/google/api_client/auth/key_utils.rb:88:in `rescue in load_key': Invalid keyfile or passphrase (ArgumentError)
        from C:/Users/sinbkk/.vagrant.d/gems/gems/google-api-client-0.8.2/lib/google/api_client/auth/key_utils.rb:80:in `load_key'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/google-api-client-0.8.2/lib/google/api_client/auth/key_utils.rb:34:in `load_from_pkcs12'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/core.rb:118:in `new_pk12_google_client'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/core.rb:85:in `initialize_google_client'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/compute.rb:1058:in `initialize'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/service.rb:115:in `new'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/compute.rb:64:in `new'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/connect_google.rb:41:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/provider.rb:45:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:480:in `state'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:141:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/vagrantfile.rb:75:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:614:in `machine'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:168:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:192:in `block in with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `each'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/plugin/v2/command.rb:174:in `with_target_vms'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:74:in `block in execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:277:in `block (2 levels) in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `tap'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:275:in `block in batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `synchronize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:274:in `batch'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/plugins/commands/up/command.rb:58:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/cli.rb:42:in `execute'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:301:in `cli'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:174:in `<main>'

**Comment by erjohnso** [comment] 2015-02-04 13:14
Great, thanks for the detail.

Can you confirm that you've specified the full absolute path to the keyfile?  Also, what you've quoted above doesn't look like the standard file extension (should be .p12), are you sure you don't have a typo in the vagrant file?  IIRC, the error message can be misleading if the keyfile can't be found.

**Comment by kulkarni-bhaskar** [comment] 2015-02-04 13:19
My bad , sorry for the trouble was stuck with the passphrase thing too much 
Thanks a ton for your help

**Comment by kulkarni-bhaskar** [comment] 2015-02-04 13:25
gone past that but now getting this

C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/models/compute/images.rb:67:in `rescue in get': class or module required for rescue clause (TypeError)
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/models/compute/images.rb:47:in `get'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/requests/compute/insert_disk.rb:77:in `insert_disk'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-1.27.0/lib/fog/google/models/compute/disk.rb:40:in `save'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/fog-core-1.28.0/lib/fog/core/collection.rb:51:in `create'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/run_instance.rb:59:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/warn_networks.rb:27:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/sync_folders.rb:32:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-proxyconf-1.5.0/lib/vagrant-proxyconf/action/only_once.rb:21:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/provision.rb:80:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/call.rb:53:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/Users/sinbkk/.vagrant.d/gems/gems/vagrant-google-0.1.4/lib/vagrant-google/action/connect_google.rb:43:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/config_validate.rb:25:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box.rb:56:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/handle_box_url.rb:9:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/warden.rb:34:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builder.rb:116:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `block in run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/busy.rb:19:in `busy'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/runner.rb:66:in `run'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:214:in `action_raw'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:191:in `block in action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/environment.rb:516:in `lock'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `call'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/machine.rb:178:in `action'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/batch_action.rb:82:in `block (2 levels) in run'

**Comment by erjohnso** [comment] 2015-02-04 14:10
Nothing obvious jumps out to me on this one. Could you try enabling debugging and see if that helps track down the problem?

```
VAGRANT_LOG=debug vagrant up --provider=google
```

That produces a lot of output and it probably contains personal info (project name, etc). If you're comfortable with this, you could paste it in a private gist and I can look it over.

FWIW, it's blowing up in fog [https://github.com/fog/fog/blob/v1.27.0/lib/fog/google/models/compute/images.rb#L47] and that leads me to believe it's not picking up your project id correctly.

I'm wondering if you have your overrides set correctly. My Vagrantfile looks like this. Perhaps you can try this and see if it works?

```
Vagrant.configure("2") do |config|
  config.vm.box = "gce"
  config.vm.synced_folder "/Users/erjohnso/tmp/", "/host-data"
  config.vm.synced_folder "/Users/erjohnso/", "/vagrant", disabled: true

  config.vm.provider :google do |google, override|
    google.google_project_id = "my-project-name"
    google.google_client_email = "foo@developer.gserviceaccount.com"
    google.google_key_location = "~/PRIVATE_KEY.p12"

    override.ssh.username = "erjohnso"
    override.ssh.private_key_path = "~/.ssh/google_compute_engine"
  end

end
```

Note that I'm on a Mac, but otherwise using the same version of vagrant and vagrant-google plugin.  With this Vagrantfile, I'm able to bring up the instance and use `vagrant ssh` to get into it.

**Comment by erjohnso** [comment] 2015-02-05 16:40
Hi @kulkarni-bhaskar - did you get everything working? Please let me know if I can help or if we've found a bug.

**Comment by erjohnso** [comment] 2015-02-11 15:19
Closing this out @kulkarni-bhaskar  - please raise it again if you're still seeing problems.

**Closed by erjohnso** 2015-02-11 15:19 UTC
Labels: question
